# Generated by Django 5.0.4 on 2024-05-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='slug',
            field=models.SlugField(editable=False, verbose_name='Слаг'),
        ),
    ]
