# Generated by Django 5.0.4 on 2024-05-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_author_slug_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='author',
            name='where_from',
            field=models.CharField(choices=[('RU', 'Россия'), ('USA', 'Америка'), ('ENG', 'Англия'), ('GER', 'Гурмания'), ('FRA', 'Франция')], max_length=4, verbose_name='Место рождения'),
        ),
    ]
