# Generated by Django 5.0.4 on 2024-05-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_author_photo_alter_author_where_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='covers/%Y/%m/%d', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='book',
            name='snippet',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отрывок'),
        ),
    ]
