# Generated by Django 5.0.4 on 2024-05-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_book_cover_book_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='aurhor',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='author',
            name='where_from',
            field=models.CharField(choices=[('RU', 'Россия'), ('USA', 'Америка'), ('ENG', 'Англия'), ('GER', 'Германия'), ('FRA', 'Франция')], max_length=4, verbose_name='Место рождения'),
        ),
    ]
