# Generated by Django 5.0.4 on 2024-05-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%d', verbose_name='Обложка'),
        ),
    ]
