# Generated by Django 5.0.4 on 2024-04-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('short_biography', models.TextField(verbose_name='Краткая биография')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('where_from', models.CharField(choices=[('RU', 'Россия'), ('USA', 'Америка'), ('ENG', 'Англия'), ('GER', 'Гурмания'), ('FRA', 'Франция')], max_length=4)),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['first_name', 'last_name'],
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
