# Generated by Django 5.0.4 on 2024-04-27 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название книги')),
                ('genre', models.CharField(choices=[('Nov', 'Новелла'), ('Dra', 'Драма'), ('Poe', 'Поэма'), ('Rom', 'Роман'), ('Epo', 'Эпос')], max_length=3, verbose_name='Жанр')),
                ('published', models.DateField(verbose_name='Дата публикации')),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('aurhor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
